#!/usr/bin/env python3
"""
bedrock_list_non_natural.py
---------------------------
List all non-natural (player-placed / crafted) blocks and entities with their
world coordinates in a Minecraft Bedrock dedicated-server world.

Usage:
    uv run --with amulet-leveldb python3 bedrock_list_non_natural.py <world_db_path>

Example:
    uv run --with amulet-leveldb python3 bedrock_list_non_natural.py \
        "/home/ubuntu/minecraft-bedrock-server/1.21.130.4/worlds/Sam World/db"

Output:
    - One line per non-natural block:   X  Y  Z  block_name
    - One line per non-natural entity:  X  Y  Z  entity_id
    - Summary table at the end
"""
import math
import os
import shutil
import struct
import sys
from collections import defaultdict

# ---------------------------------------------------------------------------
# Dependency: amulet-leveldb  (supports Bedrock's Zlib-compressed LevelDB)
# ---------------------------------------------------------------------------
try:
    from leveldb import LevelDB
except ImportError:
    print("ERROR: Install amulet-leveldb first:")
    print("  uv run --with amulet-leveldb python3 bedrock_list_non_natural.py ...")
    sys.exit(1)


# ---------------------------------------------------------------------------
# Blocks that are NATURALLY generated by world-gen (not player-placed).
# Anything NOT in this set is treated as non-natural.
# ---------------------------------------------------------------------------
NATURAL_BLOCKS = frozenset({
    # Air
    "minecraft:air", "minecraft:cave_air", "minecraft:void_air",
    # Stone family
    "minecraft:stone", "minecraft:granite", "minecraft:diorite", "minecraft:andesite",
    "minecraft:tuff", "minecraft:tuff_bricks", "minecraft:chiseled_tuff",
    "minecraft:deepslate", "minecraft:cobbled_deepslate",
    "minecraft:calcite", "minecraft:smooth_basalt",
    # Dirt family
    "minecraft:dirt", "minecraft:grass_block", "minecraft:short_grass", "minecraft:grass",
    "minecraft:podzol", "minecraft:mycelium",
    "minecraft:rooted_dirt", "minecraft:coarse_dirt", "minecraft:dirt_with_roots",
    "minecraft:moss_block", "minecraft:moss_carpet",
    "minecraft:mud", "minecraft:muddy_mangrove_roots",
    # Sand / Gravel / Clay
    "minecraft:sand", "minecraft:red_sand",
    "minecraft:gravel", "minecraft:clay",
    "minecraft:sandstone", "minecraft:red_sandstone",
    "minecraft:suspicious_sand", "minecraft:suspicious_gravel",
    # Ores (all variants)
    "minecraft:coal_ore",        "minecraft:deepslate_coal_ore",
    "minecraft:iron_ore",        "minecraft:deepslate_iron_ore",
    "minecraft:gold_ore",        "minecraft:deepslate_gold_ore",
    "minecraft:diamond_ore",     "minecraft:deepslate_diamond_ore",
    "minecraft:emerald_ore",     "minecraft:deepslate_emerald_ore",
    "minecraft:lapis_ore",       "minecraft:deepslate_lapis_ore",
    "minecraft:redstone_ore",    "minecraft:deepslate_redstone_ore",
    "minecraft:lit_redstone_ore","minecraft:lit_deepslate_redstone_ore",
    "minecraft:copper_ore",      "minecraft:deepslate_copper_ore",
    "minecraft:nether_quartz_ore","minecraft:nether_gold_ore",
    "minecraft:ancient_debris",
    # Water / Lava / Bubble
    "minecraft:water", "minecraft:flowing_water",
    "minecraft:lava",  "minecraft:flowing_lava",
    "minecraft:bubble_column",
    # Ice / Snow
    "minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice", "minecraft:frosted_ice",
    "minecraft:snow", "minecraft:snow_layer", "minecraft:powder_snow",
    # Bedrock / Obsidian (natural lava+water contact, end portal frames)
    "minecraft:bedrock", "minecraft:obsidian",
    "minecraft:end_portal_frame", "minecraft:end_portal", "minecraft:end_gateway",
    # Magma / Fire (natural underground/nether)
    "minecraft:magma", "minecraft:fire", "minecraft:soul_fire",
    # Natural tree blocks
    "minecraft:oak_log",      "minecraft:oak_leaves",
    "minecraft:spruce_log",   "minecraft:spruce_leaves",
    "minecraft:birch_log",    "minecraft:birch_leaves",
    "minecraft:jungle_log",   "minecraft:jungle_leaves",
    "minecraft:acacia_log",   "minecraft:acacia_leaves",
    "minecraft:dark_oak_log", "minecraft:dark_oak_leaves",
    "minecraft:cherry_log",   "minecraft:cherry_leaves",
    "minecraft:mangrove_log", "minecraft:mangrove_leaves",
    "minecraft:mangrove_roots",
    "minecraft:pale_oak_log", "minecraft:pale_oak_leaves",
    "minecraft:bamboo_block", "minecraft:bamboo_sapling", "minecraft:bamboo",
    # Natural sapling / plant variants
    "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling",
    "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling",
    "minecraft:cherry_sapling", "minecraft:mangrove_propagule", "minecraft:pale_oak_sapling",
    # Tall grass / ferns / vegetation
    "minecraft:tall_grass", "minecraft:fern", "minecraft:large_fern", "minecraft:dead_bush",
    "minecraft:seagrass", "minecraft:tallgrass",
    "minecraft:kelp", "minecraft:kelp_plant",
    "minecraft:cactus", "minecraft:sugar_cane",
    "minecraft:vine", "minecraft:lily_pad",
    "minecraft:glow_lichen", "minecraft:hanging_roots",
    "minecraft:big_dripleaf", "minecraft:big_dripleaf_stem",
    "minecraft:small_dripleaf",
    "minecraft:spore_blossom",
    "minecraft:azalea", "minecraft:flowering_azalea",
    "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves",
    "minecraft:cave_vines", "minecraft:cave_vines_body_with_berries", "minecraft:cave_vines_head_with_berries",
    "minecraft:twisting_vines", "minecraft:twisting_vines_plant",
    "minecraft:weeping_vines", "minecraft:weeping_vines_plant",
    "minecraft:nether_sprouts", "minecraft:warped_roots", "minecraft:crimson_roots",
    "minecraft:warped_fungus", "minecraft:crimson_fungus",
    "minecraft:bush",
    # Flowers
    "minecraft:yellow_flower", "minecraft:red_flower",
    "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium",
    "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip",
    "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy",
    "minecraft:cornflower", "minecraft:lily_of_the_valley",
    "minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony",
    "minecraft:wither_rose", "minecraft:pitcher_plant", "minecraft:torchflower",
    "minecraft:pitcher_crop", "minecraft:torchflower_crop",
    "minecraft:open_eyeblossom", "minecraft:closed_eyeblossom",
    # Pale Garden
    "minecraft:pale_moss_block", "minecraft:pale_moss_carpet",
    "minecraft:resin_clump", "minecraft:resin_block", "minecraft:resin_bricks",
    "minecraft:chiseled_resin_bricks",
    # Mushrooms (natural)
    "minecraft:brown_mushroom", "minecraft:red_mushroom",
    "minecraft:brown_mushroom_block", "minecraft:red_mushroom_block",
    "minecraft:mushroom_stem", "minecraft:huge_mushroom_1", "minecraft:huge_mushroom_2",
    # Underground features
    "minecraft:dripstone_block", "minecraft:pointed_dripstone",
    "minecraft:amethyst_block", "minecraft:budding_amethyst",
    "minecraft:amethyst_cluster", "minecraft:large_amethyst_bud",
    "minecraft:medium_amethyst_bud", "minecraft:small_amethyst_bud",
    "minecraft:sculk", "minecraft:sculk_vein", "minecraft:sculk_catalyst",
    "minecraft:sculk_shrieker", "minecraft:sculk_sensor", "minecraft:calibrated_sculk_sensor",
    # Nether natural
    "minecraft:netherrack", "minecraft:soul_sand", "minecraft:soul_soil",
    "minecraft:nether_wart_block", "minecraft:warped_wart_block",
    "minecraft:warped_nylium", "minecraft:crimson_nylium",
    "minecraft:warped_stem", "minecraft:crimson_stem",
    "minecraft:warped_hyphae", "minecraft:crimson_hyphae",
    "minecraft:basalt", "minecraft:blackstone", "minecraft:glowstone",
    "minecraft:nether_wart",  # grows naturally
    # End natural
    "minecraft:end_stone", "minecraft:chorus_plant", "minecraft:chorus_flower",
    # Infested (silverfish) blocks — world-generated in strongholds
    "minecraft:infested_stone", "minecraft:infested_cobblestone",
    "minecraft:infested_stone_bricks", "minecraft:infested_mossy_stone_bricks",
    "minecraft:infested_cracked_stone_bricks", "minecraft:infested_chiseled_stone_bricks",
    "minecraft:infested_deepslate",
    # Web (natural in mineshafts/spider spawners)
    "minecraft:cobweb", "minecraft:web",
    # Sponge (ocean monument)
    "minecraft:sponge",
    # Coral (natural underwater)
    "minecraft:brain_coral",       "minecraft:brain_coral_block",       "minecraft:dead_brain_coral_block",
    "minecraft:bubble_coral",      "minecraft:bubble_coral_block",      "minecraft:dead_bubble_coral_block",
    "minecraft:fire_coral",        "minecraft:fire_coral_block",        "minecraft:dead_fire_coral_block",
    "minecraft:horn_coral",        "minecraft:horn_coral_block",        "minecraft:dead_horn_coral_block",
    "minecraft:tube_coral",        "minecraft:tube_coral_block",        "minecraft:dead_tube_coral_block",
    "minecraft:brain_coral_fan",   "minecraft:dead_brain_coral_fan",
    "minecraft:bubble_coral_fan",  "minecraft:dead_bubble_coral_fan",
    "minecraft:fire_coral_fan",    "minecraft:dead_fire_coral_fan",
    "minecraft:horn_coral_fan",    "minecraft:dead_horn_coral_fan",
    "minecraft:tube_coral_fan",    "minecraft:dead_tube_coral_fan",
    "minecraft:coral_fan", "minecraft:coral_fan_dead", "minecraft:coral_fan_hang",
    "minecraft:coral_fan_hang2",   "minecraft:coral_fan_hang3",
    "minecraft:coral_block",
    # Lush caves
    "minecraft:big_dripleaf",
    # Naturally occurring structure components that world-gen places:
    # (cobblestone in ravines/geodes is debatable; mossy variants in swamps/dungeons)
    "minecraft:cobblestone",  "minecraft:mossy_cobblestone",
    "minecraft:stone_bricks",  "minecraft:mossy_stone_bricks",
    "minecraft:cracked_stone_bricks", "minecraft:chiseled_stone_bricks",
    # Note: the above appear in strongholds/dungeons — mark as natural world-gen
    "minecraft:gravel",
    "minecraft:monster_egg",  # legacy name for infested
})

# Entity types that spawn naturally in the world (not placed by players)
NATURAL_ENTITIES = frozenset({
    # Overworld passive
    "minecraft:cow", "minecraft:mooshroom", "minecraft:pig", "minecraft:sheep",
    "minecraft:chicken", "minecraft:rabbit", "minecraft:horse", "minecraft:donkey",
    "minecraft:mule", "minecraft:llama", "minecraft:trader_llama",
    "minecraft:wolf", "minecraft:cat", "minecraft:ocelot", "minecraft:parrot",
    "minecraft:fox", "minecraft:panda", "minecraft:polar_bear", "minecraft:turtle",
    "minecraft:bee", "minecraft:goat", "minecraft:axolotl", "minecraft:frog",
    "minecraft:tadpole", "minecraft:camel", "minecraft:sniffer",
    "minecraft:strider",  # nether passive
    # Overworld hostile
    "minecraft:zombie", "minecraft:zombie_villager", "minecraft:zombie_villager_v2",
    "minecraft:husk", "minecraft:drowned",
    "minecraft:skeleton", "minecraft:stray", "minecraft:bogged",
    "minecraft:creeper", "minecraft:spider", "minecraft:cave_spider",
    "minecraft:enderman", "minecraft:witch", "minecraft:slime",
    "minecraft:phantom", "minecraft:silverfish", "minecraft:endermite",
    "minecraft:guardian", "minecraft:elder_guardian",
    "minecraft:vindicator", "minecraft:pillager", "minecraft:ravager",
    "minecraft:evoker", "minecraft:vex",
    "minecraft:warden", "minecraft:breeze", "minecraft:creaking",
    # Nether hostile
    "minecraft:blaze", "minecraft:ghast", "minecraft:magma_cube",
    "minecraft:wither_skeleton", "minecraft:hoglin", "minecraft:zoglin",
    "minecraft:piglin", "minecraft:piglin_brute", "minecraft:zombified_piglin",
    # Neutral / misc
    "minecraft:bat", "minecraft:allay", "minecraft:shulker",
    # Villager / NPC
    "minecraft:villager", "minecraft:villager_v2", "minecraft:wandering_trader",
    "minecraft:iron_golem", "minecraft:snow_golem",
    # Water mobs
    "minecraft:cod", "minecraft:salmon", "minecraft:tropical_fish",
    "minecraft:pufferfish", "minecraft:dolphin", "minecraft:squid", "minecraft:glow_squid",
    # Bosses (naturally spawned in their domain)
    "minecraft:ender_dragon", "minecraft:wither",
    # Misc naturally appearing
    "minecraft:falling_block", "minecraft:xp_orb", "minecraft:item",
    "minecraft:lightning_bolt",
})


# ---------------------------------------------------------------------------
# Little-Endian NBT parser (Bedrock format)
# ---------------------------------------------------------------------------
TAG_END, TAG_BYTE, TAG_SHORT, TAG_INT, TAG_LONG = 0, 1, 2, 3, 4
TAG_FLOAT, TAG_DOUBLE, TAG_BYTEARRAY, TAG_STRING = 5, 6, 7, 8
TAG_LIST, TAG_COMPOUND, TAG_INTARRAY, TAG_LONGARRAY = 9, 10, 11, 12


class NBTReader:
    """Reads little-endian NBT from a bytes buffer, tracking the current offset."""

    def __init__(self, data: bytes, offset: int = 0):
        self.data = data
        self.offset = offset

    # --- primitives ---
    def _adv(self, n: int) -> int:
        o = self.offset
        if o + n > len(self.data):
            raise struct.error(
                f"buffer too small: need {n} byte(s) at offset {o}, "
                f"only {len(self.data) - o} remain"
            )
        self.offset += n
        return o

    def u8(self)  -> int: return struct.unpack_from('<B', self.data, self._adv(1))[0]
    def i8(self)  -> int: return struct.unpack_from('<b', self.data, self._adv(1))[0]
    def i16(self) -> int: return struct.unpack_from('<h', self.data, self._adv(2))[0]
    def u16(self) -> int: return struct.unpack_from('<H', self.data, self._adv(2))[0]
    def i32(self) -> int: return struct.unpack_from('<i', self.data, self._adv(4))[0]
    def i64(self) -> int: return struct.unpack_from('<q', self.data, self._adv(8))[0]
    def f32(self) -> float: return struct.unpack_from('<f', self.data, self._adv(4))[0]
    def f64(self) -> float: return struct.unpack_from('<d', self.data, self._adv(8))[0]

    def string(self) -> str:
        n = self.u16()
        raw = self.data[self.offset:self.offset + n]
        self.offset += n
        return raw.decode('utf-8', errors='replace')

    def read_payload(self, tag: int):
        if tag == TAG_END:       return None
        if tag == TAG_BYTE:      return self.i8()
        if tag == TAG_SHORT:     return self.i16()
        if tag == TAG_INT:       return self.i32()
        if tag == TAG_LONG:      return self.i64()
        if tag == TAG_FLOAT:     return self.f32()
        if tag == TAG_DOUBLE:    return self.f64()
        if tag == TAG_BYTEARRAY:
            n = self.i32()
            if n < 0 or n > len(self.data):
                raise ValueError(f"TAG_BYTEARRAY size {n} out of range")
            b = self.data[self.offset:self.offset + n]
            self.offset += n
            return b
        if tag == TAG_STRING:    return self.string()
        if tag == TAG_LIST:
            et = self.u8()
            c  = self.i32()
            if c < 0 or c > 65536:
                raise ValueError(f"TAG_LIST count {c} out of range")
            return [self.read_payload(et) for _ in range(c)]
        if tag == TAG_COMPOUND:
            d = {}
            while True:
                t = self.u8()
                if t == TAG_END:
                    break
                name = self.string()
                d[name] = self.read_payload(t)
            return d
        if tag == TAG_INTARRAY:
            n = self.i32()
            if n < 0 or n > 65536:
                raise ValueError(f"TAG_INTARRAY count {n} out of range")
            return [self.i32() for _ in range(n)]
        if tag == TAG_LONGARRAY:
            n = self.i32()
            if n < 0 or n > 65536:
                raise ValueError(f"TAG_LONGARRAY count {n} out of range")
            return [self.i64() for _ in range(n)]
        raise ValueError(f"Unknown NBT tag type: {tag}")

    def parse_root(self):
        """Parse one root NBT value (tag byte + name + payload)."""
        tag  = self.u8()
        name = self.string()
        return name, self.read_payload(tag)


def parse_nbt(data: bytes, offset: int = 0):
    """Return (nbt_dict, new_offset). Returns (None, offset) on error."""
    try:
        r = NBTReader(data, offset)
        _, nbt = r.parse_root()
        return nbt, r.offset
    except Exception:
        return None, offset


# ---------------------------------------------------------------------------
# Subchunk decoder
# ---------------------------------------------------------------------------
def decode_subchunk_blocks(data: bytes, chunk_x: int, chunk_z: int, sub_y_signed: int):
    """
    Decode a Bedrock subchunk (version 8 or 9) and yield
    (world_x, world_y, world_z, block_name) for every non-air block
    whose name is NOT in NATURAL_BLOCKS.

    sub_y_signed : signed sub-chunk Y index (world_y_base = sub_y_signed * 16)
    """
    if not data or len(data) < 3:
        return

    version = data[0]
    if version not in (8, 9):
        # Version 1 (legacy) or unknown — skip detailed decode
        return

    num_layers = data[1]
    if num_layers == 0:
        return

    # Version 9 stores the sub-chunk Y index as an extra byte at offset 2
    # before the storage layer data, so skip it.
    offset = 3 if version == 9 else 2
    base_y = sub_y_signed * 16

    # We only need the first (primary) storage layer
    storage_header = data[offset]; offset += 1
    bits_per_block = storage_header >> 1
    # bit 0 = is_network_palette (should be 0 for disk format)
    # Valid disk values: 0,1,2,3,4,5,6,8,16  — reject anything larger
    if bits_per_block > 16:
        return

    try:
        if bits_per_block == 0:
            # All 4096 blocks are the single palette entry (palette[0]).
            # Format: palette_size (int32, always 1) + 1 NBT compound.
            # NOTE: there is NO packed word array when bits_per_block == 0.
            if offset + 4 > len(data):
                return
            palette_size = struct.unpack_from('<i', data, offset)[0]; offset += 4
            if palette_size < 1 or palette_size > 4096:
                return
            nbt, offset = parse_nbt(data, offset)
            block_name = nbt.get('name', 'minecraft:air') if nbt else 'minecraft:air'
            if block_name not in NATURAL_BLOCKS:
                # Every one of the 4096 blocks in this subchunk is non-natural
                for idx in range(4096):
                    lx = idx % 16
                    lz = (idx // 16) % 16
                    ly = idx // 256
                    yield (chunk_x * 16 + lx,
                           base_y + ly,
                           chunk_z * 16 + lz,
                           block_name)
        else:
            blocks_per_word = 32 // bits_per_block
            word_count = math.ceil(4096 / blocks_per_word)

            if offset + word_count * 4 > len(data):
                return

            words = struct.unpack_from(f'<{word_count}I', data, offset)
            offset += word_count * 4

            # Unpack block indices from bit-packed words
            mask = (1 << bits_per_block) - 1
            indices = []
            for word in words:
                for shift in range(0, 32, bits_per_block):
                    indices.append((word >> shift) & mask)
                    if len(indices) == 4096:
                        break
                if len(indices) == 4096:
                    break

            # Read palette
            if offset + 4 > len(data):
                return
            palette_size = struct.unpack_from('<i', data, offset)[0]; offset += 4
            if palette_size < 1 or palette_size > 4096:
                return
            palette = []
            for _ in range(palette_size):
                nbt, offset = parse_nbt(data, offset)
                palette.append(nbt.get('name', 'minecraft:air') if nbt else 'minecraft:air')

            if not palette:
                return

            # Yield non-natural blocks
            for idx, pal_idx in enumerate(indices):
                if pal_idx >= len(palette):
                    continue
                block_name = palette[pal_idx]
                if block_name in NATURAL_BLOCKS:
                    continue
                lx = idx % 16
                lz = (idx // 16) % 16
                ly = idx // 256
                yield (chunk_x * 16 + lx,
                       base_y + ly,
                       chunk_z * 16 + lz,
                       block_name)

    except Exception:
        return


# ---------------------------------------------------------------------------
# Entity decoder
# ---------------------------------------------------------------------------
def decode_entity(data: bytes):
    """
    Parse an actorprefix NBT record and return (entity_id, x, y, z) or None.
    """
    nbt, _ = parse_nbt(data)
    if not isinstance(nbt, dict):
        return None
    eid = nbt.get('id') or nbt.get('identifier')
    if not isinstance(eid, str):
        return None
    pos = nbt.get('Pos')
    if isinstance(pos, list) and len(pos) >= 3:
        return eid, pos[0], pos[1], pos[2]
    return None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def ordinal(n: int) -> str:
    """Return '1st', '2nd', '3rd', '4th', … for a positive integer."""
    if 11 <= (n % 100) <= 13:
        return f"{n}th"
    return f"{n}" + {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")


def open_db_readonly(db_path: str) -> LevelDB:
    """
    Open a Bedrock LevelDB without acquiring the exclusive LOCK file.
    Standard LevelDB has no built-in read-only mode, so we temporarily
    move any existing LOCK file aside, open the DB (which creates a new
    LOCK), immediately remove that new LOCK, then restore the original.
    This lets the script run alongside a live server on a different world
    copy, or against an idle backup without interference.
    """
    lock_path   = os.path.join(db_path, "LOCK")
    backup_path = lock_path + ".scan_bak"

    original_existed = os.path.exists(lock_path)
    if original_existed:
        shutil.move(lock_path, backup_path)

    try:
        db = LevelDB(db_path, create_if_missing=False)
        # Remove the new LOCK our open just created — we won't be writing.
        if os.path.exists(lock_path):
            os.remove(lock_path)
    finally:
        # Always restore the original lock (if there was one).
        if original_existed and os.path.exists(backup_path):
            if os.path.exists(lock_path):
                os.remove(lock_path)
            shutil.move(backup_path, lock_path)

    return db


# ---------------------------------------------------------------------------
# Main scanner  (streams results to stdout immediately)
# ---------------------------------------------------------------------------
def scan_world(db_path: str):
    print(f"Opening world DB: {db_path}", flush=True)
    try:
        db = open_db_readonly(db_path)
    except Exception as e:
        print(f"ERROR: Cannot open DB: {e}")
        sys.exit(1)

    # Counters only — no coordinate lists kept in memory.
    block_counts:  dict[str, int] = defaultdict(int)
    entity_counts: dict[str, int] = defaultdict(int)

    subchunks_scanned = 0
    entities_scanned  = 0
    kv_count          = 0

    print("\n[NON-NATURAL BLOCKS]")
    print(f"{'X':>8}  {'Y':>5}  {'Z':>8}  Block")
    print(f"{'─'*8}  {'─'*5}  {'─'*8}  {'─'*35}")

    for key, val in db.iterate():
        kv_count += 1

        # ---- Subchunk block data (tag byte = 47 = 0x2F) ----
        # Overworld (no dim): 10-byte key = cx(4) + cz(4) + tag(1) + sub_y(1)
        # Other dims:         14-byte key = cx(4) + cz(4) + dim(4) + tag(1) + sub_y(1)
        if (len(key) == 10 and key[8] == 47) or (len(key) == 14 and key[12] == 47):
            # print(f"  -- {ordinal(kv_count)} iteration being processed with subchunk data --", flush=True)
            cx, cz   = struct.unpack_from('<ii', key, 0)
            tag_off  = 8 if len(key) == 10 else 12
            sub_byte = key[tag_off + 1]
            sub_y    = struct.unpack('b', bytes([sub_byte]))[0]  # signed

            subchunks_scanned += 1
            for wx, wy, wz, bname in decode_subchunk_blocks(val, cx, cz, sub_y):
                print(f"{wx:>8}  {wy:>5}  {wz:>8}  {bname}", flush=True)
                block_counts[bname] += 1

        # ---- Entity data (actorprefix) ----
        elif key[:11] == b"actorprefix":
            # print(f"  -- {ordinal(kv_count)} iteration being processed with entity data --", flush=True)
            entities_scanned += 1
            result = decode_entity(val)
            if result:
                eid, ex, ey, ez = result
                if eid not in NATURAL_ENTITIES:
                    print(f"\n[ENTITY]  {ex:.0f}  {ey:.0f}  {ez:.0f}  {eid}", flush=True)
                    entity_counts[eid] += 1

    db.close()
    return block_counts, entity_counts, subchunks_scanned, entities_scanned


# ---------------------------------------------------------------------------
# Summary  (printed after streaming is complete)
# ---------------------------------------------------------------------------
def print_summary(block_counts, entity_counts, subchunks_scanned, entities_scanned):
    total_blocks   = sum(block_counts.values())
    total_entities = sum(entity_counts.values())

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"  Subchunks scanned : {subchunks_scanned:,}")
    print(f"  Entities scanned  : {entities_scanned:,}")
    print(f"  Non-natural blocks: {total_blocks:,} total, {len(block_counts)} unique types")
    print(f"  Non-natural entit.: {total_entities:,} total, {len(entity_counts)} unique types")

    if block_counts:
        print("\n  Block type counts:")
        for bname, cnt in sorted(block_counts.items(), key=lambda x: -x[1]):
            print(f"    {cnt:6,}  {bname}")

    if entity_counts:
        print("\n  Entity type counts:")
        for eid, cnt in sorted(entity_counts.items(), key=lambda x: -x[1]):
            print(f"    {cnt:6,}  {eid}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    db_path = sys.argv[1]
    block_counts, entity_counts, subchunks_scanned, entities_scanned = scan_world(db_path)
    print_summary(block_counts, entity_counts, subchunks_scanned, entities_scanned)
