git clone git@github.com:hczhu/code_recipes.git
git clone https://github.com/fluentpython/example-code-2e.git
git clone https://github.com/openai/gpt-2
git clone https://github.com/pytorch-labs/gpt-fast.git
git clone https://github.com/k8sgpt-ai/k8sgpt.git
git clone https://github.com/Lightning-AI/lit-gpt.git
git clone https://github.com/facebookresearch/llama.git
git clone https://github.com/ggerganov/llama.cpp.git
git clone https://github.com/karpathy/llama2.c.git
git clone https://github.com/m3db/m3.git
git clone https://github.com/karpathy/minGPT.git
git clone https://github.com/karpathy/nanoGPT.git
git clone https://github.com/jmorganca/ollama.git
git clone https://github.com/ray-project/ray.git
git clone https://github.com/anyscale/academy.git
git clone https://github.com/lucidrains/reformer-pytorch.git
git clone https://github.com/huggingface/transformers.git
git clone https://github.com/openai/triton.git
